title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/Srujna">GitHub</a>
  
  <br>   
  I am learning on Data Science, machine learning through IIIT-Bangalore via upgrad.
  <br>
  </p>



theme: jekyll-theme-minimal
